const Cards = [["Bad",
"Mildly addictive",
"Hot",
"Normal",
"Colorless",
"Low calorie",
"Feels bad",
"Inessential",
"Cheap",
"Underrated weapon",
"Rare",
"Unsexy emoji",
"Easy subject",
"Unknown",
"Difficult to use",
"Tired",
"Dirty",
"Requires luck",
"Flavorless",
"Boring topic",
"Bad actor",
"Basic",
"Dangerous job",
"Fantasy",
"Casual",
"Underpaid",
"Dry",
"Underrated skill",
"Forbidden",
"Sad song",
"Fragile",
"Geek",
"Good",
"Worst day of the year",
"Bad habit",
"Cat person",
"Guilty pleasure",
"Untalented",
"Dark",
"Underrated actor",
"Hard to find",
"Ugly man",
"Hard to remember",
"Lowbrow",
"Unhealthy",
"Bad man",
"Historically important",
"Hairless",
"Inflexible",
"Normal pet",
"Introvert",
"Book was better",
"Bad movie",
"Ugly",
"Happens slowly",
"Job",
"Loved",
"The Light Side of the Force",
"Bad pizza topping",
"Dystopia",
"Mature person",
"Underrated thing to own",
"Mean person",
"Action movie",
"Mental activity",
"Uncontroversial topic",
"Need",
"Dry food",
"Normal thing to own",
"Straight",
"Bad person",
"80s",
"Ethical to eat",
"Movie",
"Optional",
"Underrated letter of the alphabet",
"Ordinary",
"Hard to pronounce",
"Low quality",
"Unsexy animal",
"Plain",
"Has a bad reputation",
"Poorly made",
"Not a sandwich",
"Quiet place",
"Comedy",
"Dangerous",
"Culturally significant",
"Replaceable",
"Worst athlete of all time",
"Role model",
"Useless major",
"Peaceful",
"Underrated movie",
"Rough",
"Bad for you",
"Round",
"Proof that God exists",
"Sad movie",
"Waste of time",
"Scary animal",
"Mainstream",
"Short lived",
"Nobody does it",
"Smells bad",
"Star Wars",
"Snack",
"Least evil company",
"Soft",
"Sustenance",
"Square",
"Better hot",
"Stupid",
"Artisanal",
"Bad superpower",
"Ineffective",
"Unbelievable",
"Trashy",
"Temporary",
"Looks like a person",
"Tastes bad",
"Sport",
"Uncool",
"Worst living person",
"Underrated",
"Messy food",
"Unethical",
"Bad gift",
"Unfashionable",
"Freedom fighter",
"Unforgiveable",
"Failure",
"Harmless",
"Gryffindor",
"Unhygienic",
"Bad music",
"Useless",
"Movie that Godzilla would ruin",
"Unimportant",
"Easy to spell",
"Vice",
"Underrated musician",
"Unpopular activity",
"Divided",
"Unreliable",
"Easy to kill",
"Unstable",
"Round animal",
"Bad TV show",
"Traditionally masculine",
"Useless body part",
"Fad",
"Weak",
"Disgusting cereal",
"Useless invention",
"Liberal",
"Unpopular",
"Friend",
"Boring",
"Smelly in a bad way",
"Villain",
"Underrated thing to do",
"Useless in an emergency",
"For kids",
"Wise",
"Easy to do",
"Worthless",
"Nature",
"Dictatorship",
"Normal greeting",
"Dog name",
"Non-partisan",
"Limited",
"Casual event",
"Bad investment",
"Small talk",
"Mild",
"Religious",
"Not art",
"Illegal",
"Popular",
"Out of control",
"Quiet",
"Unsexy Pokemon",
"Secret",
"Too small",
"Short",
"Worst year in history",
"Socialist",
"Little known fact",
"Stationary",
"Local issue",
"Talent",
"Worst era to time travel",
"The worst",
"Small number",
"True ",
"Old fashioned",
"Ugly word",
"Small",
"Unnatural",
"Genuine person",
"Derivative",
"Etiquette",
"Unsexy color",
"Benefits you",
"Powerless",
"Doesn't vape",
"Fruit",
"Science",
"Funny topic",
"Limp",
"Guilty pleasure",
"Gossip",
"Hard to sit on",
"Not enough",
"Horizontal",
"Unscented",
"Huggable",
"Heterogeneous",
"Inclusive",
"Bad dog breed",
"Art",
"One hit wonder",
"Bad advice",
"Tick",
"Bad candy",
"Traditional",
"Bad mouthfeel",
"Illegal",
"Deep thought",
"Bad school",
"Never on time",
"Won't live to 100",
"Bad Disney character",
"Similar",
"Bad president",
"Weird",
"Famous",
"Least powerful god",
"Boring person",
"Underrated book",
"Conventional wisdom",
"Worst chore",
"Endangered species",
"Blue",
"Thrilling",
"Nerd",
"Expected",
"Person you could beat up",
"Unreasonable phobia",
"Underrated game",
],["Good",
"Highly addictive",
"Cold",
"Weird",
"Colorful",
"High calorie",
"Feels good",
"Essential",
"Expensive",
"Overrated weapon",
"Common",
"Sexy emoji",
"Hard subject",
"Famous",
"Easy to use",
"Wired",
"Clean",
"Requires skill",
"Flavorful",
"Fascinating topic",
"Good actor",
"Hipster",
"Safe job",
"Sci-Fi",
"Formal",
"Overpaid",
"Wet",
"Overrated skill",
"Encouraged",
"Happy song",
"Durable",
"Dork",
"Evil",
"Best day of the year",
"Good habit",
"Dog person",
"Openly love",
"Talented",
"Light",
"Overrated actor",
"Easy to find",
"Beautiful man",
"Easy to remember",
"Highbrow",
"Healthy",
"Good man",
"Historically irrelevant",
"Hairy",
"Flexible",
"Exotic pet",
"Extrovert",
"Movie was better",
"Good movie",
"Beautiful",
"Happens suddenly",
"Career",
"Hated",
"The Dark Side of the Force",
"Good pizza topping",
"Utopia",
"Immature person",
"Overrated thing to own",
"Nice person",
"Adventure movie",
"Physical activity",
"Controversial topic",
"Want",
"Wet food",
"Weird thing to own",
"Curvy",
"Good person",
"90s",
"Unethical to eat",
"Film",
"Mandatory",
"Overrated letter of the alphabet",
"Extraordinary",
"Easy to pronounce",
"High quality",
"Sexy animal",
"Fancy",
"Has a good reputation",
"Well made",
"A sandwich",
"Loud place",
"Drama",
"Safe",
"Culturally insignificant",
"Irreplaceable",
"Greatest athlete of all time",
"Bad influence",
"Useful major",
"Warlike",
"Overrated movie",
"Smooth",
"Good for you",
"Pointy",
"Proof that God doesn't exist",
"Happy movie",
"Good use of time",
"Nice animal",
"Niche",
"Long lived",
"Everybody does it",
"Smells good",
"Star Trek",
"Meal",
"Most evil company",
"Hard",
"Haute cuisine",
"Round",
"Better cold",
"Brilliant",
"Mass produced",
"Good superpower",
"Effective",
"Believable",
"Classy",
"Permanent",
"Doesn't look like a person",
"Tastes good",
"Game",
"Cool",
"Greatest living person",
"Overrated",
"Clean food",
"Ethical",
"Good gift",
"Fashionable",
"Terrorist",
"Forgiveable",
"Masterpiece",
"Harmful",
"Slytherin",
"Hygienic",
"Good music",
"Useful",
"Movie that Godzilla would improve",
"Important",
"Hard to spell",
"Virtue",
"Overrated musician",
"Popular activity",
"Whole",
"Reliable",
"Hard to kill",
"Stable",
"Pointy animal",
"Good TV show",
"Traditionally feminine",
"Useful body part",
"Classic",
"Strong",
"Delicious cereal",
"Useful invention",
"Conservative",
"Popular",
"Enemy",
"Exciting",
"Smelly in a good way",
"Hero",
"Overrated thing to do",
"Useful in an emergency",
"For adults",
"Intelligent",
"Hard to do",
"Priceless",
"Nurture",
"Democracy",
"Weird greeting",
"Cat name",
"Partisan",
"Infinite",
"Formal event",
"Good investment",
"Heavy topic",
"Spicy",
"Sacrilegious",
"Art",
"Prohibited",
"Elitist",
"In control",
"Loud",
"Sexy Pokemon",
"Public knowledge",
"Too big",
"Long",
"Best year in history",
"Capitalist",
"Well known fact",
"Mobile",
"Global issue",
"Skill",
"Best era to time travel",
"The best",
"Large number",
"FALSE",
"Avant garde",
"Beautiful word",
"Tiny",
"Natural",
"Phony person",
"Original",
"Manners",
"Sexy color",
"Benefits everyone",
"Powerful",
"Vapes",
"Vegetable",
"Pseudoscience",
"Serious topic",
"Firm",
"Actually just bad",
"News",
"Easy to sit on",
"Too much",
"Vertical",
"Scented",
"Not huggable",
"Homogenous",
"Exclusive",
"Good dog breed",
"Commerce",
"Pop icon",
"Good advice",
"Tock",
"Good candy",
"Radical",
"Good mouthfeel",
"Legal",
"Shallow thought",
"Good school",
"Always on time",
"Will live to 100",
"Good Disney character",
"Identical",
"Good president",
"Strange",
"Infamous",
"Most powerful god",
"Fun person",
"Overrated book",
"Fringe belief",
"Best chore",
"Overpopulated species",
"Green",
"Terrifying",
"Jock",
"Unexpected",
"Person who would beat you up",
"Reasonable phobia",
"Overrated game",
]]
let usedCards = [[],[]];
let indices = [];
for (let i = 1; i <= Cards[0].length; i++) {
    indices.push(i);
}

function randi() { // min and max included 
  max = indices.length;
  min = 1;
  r = Math.floor(Math.random() * (max - min + 1) + min);
  return r
}

function next() {
  if (indices.length > 0) {
    let card = randi();
    document.querySelector('.leftCard').innerText = Cards[0][card];
    document.querySelector('.rightCard').innerText = Cards[1][card];
    indices.splice(r,1);
  }
  else if (indices.length === 0) {
    alert('Out of cards!');
    location.reload();
  }
}